-- =======================================================
-- CATALOGO DE SERVICIOS TCT (Actualizado 2025)
-- =======================================================
DELETE FROM catalogo_servicios;

INSERT INTO catalogo_servicios (id, categoria, nombre, unidad, precio_unit, observacion) VALUES
('sys_cam_unidad','servicios_especiales','Instalación de cámara de seguridad (por unidad)','unidad',95.00,''),
('sys_cam_kit4','servicios_especiales','Kit residencial 4 cámaras + DVR de 4 canales + accesorios básicos + instalación','sistema',650.00,''),
('sys_cam_kit8','servicios_especiales','Kit residencial 8 cámaras + DVR de 8 canales + accesorios básicos + instalación','sistema',1160.00,''),
('sys_cam_equipo','servicios_especiales','Revision tecnica o formateo de equipo o configuracion de equipos CCTV','sistema',75.00,''),
('sys_alarma_basic','servicios_especiales','Kit residencial de alarma básico central inalambrica de 48 zonas + 4 sensores + instalación','sistema',320.00,''),
('sys_automacion_ligera','servicios_especiales','Automatización de luces y tomacorrientes (iluminación + acceso inteligente) por unidad','sistema',55.00,'Si requiere mas de 2 unidades, el precio es menor, cotizar como sistema completo'),
('sys_cctv_comercial','servicios_especiales','Kit comercial 32 cámaras + DVR de 32 canales + accesorios básicos + disco duro de 4TB + instalación','proyecto',3650.00,''),
('sys_control_acceso','servicios_especiales','Kit control de acceso con 1 lectores + 5 token + cerradura electromagnetica + boton de salida + instalación','punto',250.00,''),
('sys_punto_red','servicios_especiales','Instalación de punto de red estructurada (cableado, conectorización, prueba)','unidad',95.00,''),
('sys_redes_cableado','servicios_especiales','Instalacion de cableado de red estructural','metro lineal',4.50,''),
('sys_alarma_incendio','servicios_especiales','Sistema de alarma contra incendio','sistema',1200.00,''),
('sys_fuentes_respaldo','servicios_especiales','Fuente de poder o UPS para sistemas de seguridad','unidad',180.00,''),
('sys_monitoring_servicio','servicios_especiales','Servicio de monitoreo mensual de seguridad','mes',45.00,''),
('sys_sensor_movimiento','servicios_especiales','Sensor de movimiento para sistema de alarma','unidad',90.00,''),
('sys_videoportero','servicios_especiales','Videoportero con control remoto y cámara integrada','unidad',220.00,''),
('sys_iluminacion_seguridad','servicios_especiales','Iluminación exterior de seguridad LED con sensor','lote',400.00,''),
('sys_domotica_residencial','servicios_especiales','Sistema domótico residencial completo','sistema',800.00,''),
('sys_automatizacion_comercial','servicios_especiales','Automatización comercial (integración de sistemas)','proyecto',2000.00,''),
('sys_cableado_videosurv','servicios_especiales','Cableado para video vigilancia (por cámara)','unidad',60.00,''),
('sys_antena_externa_cam','servicios_especiales','Antena externa para cámara remota','unidad',120.00,''),
('sys_sensor_magnetico','servicios_especiales','Sensor magnético de apertura de puerta o ventana','unidad',80.00,''),
('sys_intercom_general','servicios_especiales','Intercomunicador general con videoportero','unidad',300.00,''),
('sys_red_wifi_piso','servicios_especiales','Red Wi-Fi institucional por piso','piso',900.00,''),
('sys_control_clima_intel','servicios_especiales','Control climático inteligente (HVAC conectado)','sistema',650.00,''),
('sys_panel_solar_seg','servicios_especiales','Integración de panel solar para respaldo de seguridad','sistema',1100.00,''),
('sys_mantenimiento_seguridad','servicios_especiales','Mantenimiento anual de sistema de seguridad','año',150.00,''),
('sys_inspeccion_tecnica','servicios_especiales','Inspección técnica de sistemas especiales','servicio',200.00,''),
('con_obra_gris','construccion','Obra gris básica','m²',550.00,''),
('con_acabados_medios','construccion','Construcción con acabados medios','m²',800.00,''),
('con_acabados_altos','construccion','Construcción con acabados de lujo','m²',1300.00,''),
('con_pintura_monocapa','construccion','Pintura monocapa exterior','m²',4.00,''),
('con_repello_muro','construccion','Repello de muro interior/exterior','m²',6.00,''),
('con_demolicion','construccion','Demolición controlada','m²',15.00,''),
('con_baldosa_estandar','construccion','Colocación de baldosas estándar','m²',10.00,''),
('con_hormigon_piso','construccion','Sustrato de hormigón para piso','m²',30.00,''),
('con_vidrio_ventana','construccion','Instalación de vidrio templado o ventana','unidad',120.00,''),
('con_carpinteria_madera','construccion','Carpintería en madera (puertas, closets, molduras)','metro lineal',50.00,''),
('con_techo_metalico','construccion','Techo metálico o de lámina con estructura','m²',45.00,''),
('con_plomeria_basica','construccion','Instalación de plomería básica','lote',500.00,''),
('con_electricidad_basica','construccion','Instalación eléctrica básica','m²',20.00,''),
('con_electricidad_avanzada','construccion','Instalación eléctrica avanzada','m²',35.00,''),
('con_impermeabilizacion','construccion','Impermeabilización de techo o terraza','m²',8.00,''),
('con_aire_acondicionado','construccion','Instalación de aire acondicionado tipo split','unidad',450.00,''),
('con_fachada_pintura','construccion','Pintura de fachada premium','m²',6.50,''),
('con_bano_completo','construccion','Renovación de baño completo estándar','proyecto',2500.00,''),
('con_cocina_completa','construccion','Renovación de cocina completa estándar','proyecto',4000.00,''),
('con_piso_lujo','construccion','Acabado de lujo en piso (mármol o granito)','m²',120.00,''),
('con_tuberia_galvanizada','construccion','Instalación de tubería galvanizada','metro lineal',18.00,''),
('con_ventanas_doblevidrio','construccion','Instalación de ventanas doble vidrio','unidad',300.00,''),
('con_rejas_seguridad','construccion','Instalación de rejas de seguridad estándar','metro lineal',75.00,''),
('con_paisajismo_basico','construccion','Paisajismo básico y jardinería','lote',1200.00,''),
('con_drenaje_pluvial','construccion','Sistema de drenaje pluvial','metro lineal',40.00,''),
('con_puerta_seguridad','construccion','Instalación de puerta de seguridad metálica','unidad',550.00,''),
('con_tablaroca_division','construccion','Construcción de muro divisorio de tablaroca','m²',25.00,''),
('con_escaleras_metalicas','construccion','Instalación de escaleras metálicas decorativas','proyecto',3500.00,''),
('con_galeria_cristal','construccion','Galería de cristal o aluminio','m²',180.00,'');
